
controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    lekiwi_controller:
      type: omni_wheel_drive_controller/OmniWheelDriveController
 
    so100_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/GripperActionController


lekiwi_controller:
  ros__parameters:
    wheel_offset: 0.0
    wheel_names:
      [
        "ST3215_Servo_Motor-v1-2_Revolute-60",
        "ST3215_Servo_Motor-v1-1_Revolute-62",
        "ST3215_Servo_Motor-v1_Revolute-64",
      ]

    robot_radius: 0.20
    wheel_radius: 0.05

    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    open_loop: false
    position_feedback: true
    enable_odom_tf: true
    cmd_vel_timeout: 0.5
    publish_limited_velocity: true
    use_sim_time: true
so100_controller:
  ros__parameters:
    joints:
      - STS3215_03a-v1_Revolute-45
      - STS3215_03a-v1-1_Revolute-49
      - STS3215_03a-v1-2_Revolute-51
      - STS3215_03a-v1-3_Revolute-53
      - STS3215_03a_Wrist_Roll-v1_Revolute-55
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
gripper_controller:
  ros__parameters:
    joint: STS3215_03a-v1-4_Revolute-57